<?php

declare(strict_types=1);

namespace ISO;

/**
 * Extract of ISO4217
 * @see https://en.wikipedia.org/wiki/ISO_4217
 */
enum Currency: string
{
    case AED = 'AED';
    case AFN = 'AFN';
    case ALL = 'ALL';
    case AMD = 'AMD';
    case ANG = 'ANG';
    case AOA = 'AOA';
    case ARS = 'ARS';
    case AUD = 'AUD';
    case AWG = 'AWG';
    case AZN = 'AZN';
    case BAM = 'BAM';
    case BBD = 'BBD';
    case BDT = 'BDT';
    case BGN = 'BGN';
    case BHD = 'BHD';
    case BIF = 'BIF';
    case BMD = 'BMD';
    case BND = 'BND';
    case BOB = 'BOB';
    case BOV = 'BOV';
    case BRL = 'BRL';
    case BSD = 'BSD';
    case BTN = 'BTN';
    case BWP = 'BWP';
    case BYN = 'BYN';
    case BZD = 'BZD';
    case CAD = 'CAD';
    case CDF = 'CDF';
    case CHE = 'CHE';
    case CHF = 'CHF';
    case CHW = 'CHW';
    case CLF = 'CLF';
    case CLP = 'CLP';
    case CNY = 'CNY';
    case COP = 'COP';
    case COU = 'COU';
    case CRC = 'CRC';
    case CUC = 'CUC';
    case CUP = 'CUP';
    case CVE = 'CVE';
    case CZK = 'CZK';
    case DJF = 'DJF';
    case DKK = 'DKK';
    case DOP = 'DOP';
    case DZD = 'DZD';
    case EGP = 'EGP';
    case ERN = 'ERN';
    case ETB = 'ETB';
    case EUR = 'EUR';
    case FJD = 'FJD';
    case FKP = 'FKP';
    case GBP = 'GBP';
    case GEL = 'GEL';
    case GHS = 'GHS';
    case GIP = 'GIP';
    case GMD = 'GMD';
    case GNF = 'GNF';
    case GTQ = 'GTQ';
    case GYD = 'GYD';
    case HKD = 'HKD';
    case HNL = 'HNL';
    case HRK = 'HRK';
    case HTG = 'HTG';
    case HUF = 'HUF';
    case IDR = 'IDR';
    case ILS = 'ILS';
    case INR = 'INR';
    case IQD = 'IQD';
    case IRR = 'IRR';
    case ISK = 'ISK';
    case JMD = 'JMD';
    case JOD = 'JOD';
    case JPY = 'JPY';
    case KES = 'KES';
    case KGS = 'KGS';
    case KHR = 'KHR';
    case KMF = 'KMF';
    case KPW = 'KPW';
    case KRW = 'KRW';
    case KWD = 'KWD';
    case KYD = 'KYD';
    case KZT = 'KZT';
    case LAK = 'LAK';
    case LBP = 'LBP';
    case LKR = 'LKR';
    case LRD = 'LRD';
    case LSL = 'LSL';
    case LYD = 'LYD';
    case MAD = 'MAD';
    case MDL = 'MDL';
    case MGA = 'MGA';
    case MKD = 'MKD';
    case MMK = 'MMK';
    case MNT = 'MNT';
    case MOP = 'MOP';
    case MRU = 'MRU';
    case MUR = 'MUR';
    case MVR = 'MVR';
    case MWK = 'MWK';
    case MXN = 'MXN';
    case MXV = 'MXV';
    case MYR = 'MYR';
    case MZN = 'MZN';
    case NAD = 'NAD';
    case NGN = 'NGN';
    case NIO = 'NIO';
    case NOK = 'NOK';
    case NPR = 'NPR';
    case NZD = 'NZD';
    case OMR = 'OMR';
    case PAB = 'PAB';
    case PEN = 'PEN';
    case PGK = 'PGK';
    case PHP = 'PHP';
    case PKR = 'PKR';
    case PLN = 'PLN';
    case PYG = 'PYG';
    case QAR = 'QAR';
    case RON = 'RON';
    case RSD = 'RSD';
    case RUB = 'RUB';
    case RWF = 'RWF';
    case SAR = 'SAR';
    case SBD = 'SBD';
    case SCR = 'SCR';
    case SDG = 'SDG';
    case SEK = 'SEK';
    case SGD = 'SGD';
    case SHP = 'SHP';
    case SLL = 'SLL';
    case SOS = 'SOS';
    case SRD = 'SRD';
    case SSP = 'SSP';
    case STN = 'STN';
    case SVC = 'SVC';
    case SYP = 'SYP';
    case SZL = 'SZL';
    case THB = 'THB';
    case TJS = 'TJS';
    case TMT = 'TMT';
    case TND = 'TND';
    case TOP = 'TOP';
    case TRY = 'TRY';
    case TTD = 'TTD';
    case TWD = 'TWD';
    case TZS = 'TZS';
    case UAH = 'UAH';
    case UGX = 'UGX';
    case USD = 'USD';
    case USN = 'USN';
    case UYI = 'UYI';
    case UYU = 'UYU';
    case UYW = 'UYW';
    case UZS = 'UZS';
    case VED = 'VED';
    case VES = 'VES';
    case VND = 'VND';
    case VUV = 'VUV';
    case WST = 'WST';
    case XAF = 'XAF';
    case XAG = 'XAG';
    case XAU = 'XAU';
    case XBA = 'XBA';
    case XBB = 'XBB';
    case XBC = 'XBC';
    case XBD = 'XBD';
    case XCD = 'XCD';
    case XDR = 'XDR';
    case XOF = 'XOF';
    case XPD = 'XPD';
    case XPF = 'XPF';
    case XPT = 'XPT';
    case XSU = 'XSU';
    case XTS = 'XTS';
    case XUA = 'XUA';
    case XXX = 'XXX';
    case YER = 'YER';
    case ZAR = 'ZAR';
    case ZMW = 'ZMW';
    case ZWL = 'ZWL';

    public function getISO4127Code(): string
    {
        return match ($this) {
            self::AED => '784',
            self::AFN => '971',
            self::ALL => '008',
            self::AMD => '051',
            self::ANG => '532',
            self::AOA => '973',
            self::ARS => '032',
            self::AUD => '036',
            self::AWG => '533',
            self::AZN => '944',
            self::BAM => '977',
            self::BBD => '052',
            self::BDT => '050',
            self::BGN => '975',
            self::BHD => '048',
            self::BIF => '108',
            self::BMD => '060',
            self::BND => '096',
            self::BOB => '068',
            self::BOV => '984',
            self::BRL => '986',
            self::BSD => '044',
            self::BTN => '064',
            self::BWP => '072',
            self::BYN => '933',
            self::BZD => '084',
            self::CAD => '124',
            self::CDF => '976',
            self::CHE => '947',
            self::CHF => '756',
            self::CHW => '948',
            self::CLF => '990',
            self::CLP => '152',
            self::CNY => '156',
            self::COP => '170',
            self::COU => '970',
            self::CRC => '188',
            self::CUC => '931',
            self::CUP => '192',
            self::CVE => '132',
            self::CZK => '203',
            self::DJF => '262',
            self::DKK => '208',
            self::DOP => '214',
            self::DZD => '012',
            self::EGP => '818',
            self::ERN => '232',
            self::ETB => '230',
            self::EUR => '978',
            self::FJD => '242',
            self::FKP => '238',
            self::GBP => '826',
            self::GEL => '981',
            self::GHS => '936',
            self::GIP => '292',
            self::GMD => '270',
            self::GNF => '324',
            self::GTQ => '320',
            self::GYD => '328',
            self::HKD => '344',
            self::HNL => '340',
            self::HRK => '191',
            self::HTG => '332',
            self::HUF => '348',
            self::IDR => '360',
            self::ILS => '376',
            self::INR => '356',
            self::IQD => '368',
            self::IRR => '364',
            self::ISK => '352',
            self::JMD => '388',
            self::JOD => '400',
            self::JPY => '392',
            self::KES => '404',
            self::KGS => '417',
            self::KHR => '116',
            self::KMF => '174',
            self::KPW => '408',
            self::KRW => '410',
            self::KWD => '414',
            self::KYD => '136',
            self::KZT => '398',
            self::LAK => '418',
            self::LBP => '422',
            self::LKR => '144',
            self::LRD => '430',
            self::LSL => '426',
            self::LYD => '434',
            self::MAD => '504',
            self::MDL => '498',
            self::MGA => '969',
            self::MKD => '807',
            self::MMK => '104',
            self::MNT => '496',
            self::MOP => '446',
            self::MRU => '929',
            self::MUR => '480',
            self::MVR => '462',
            self::MWK => '454',
            self::MXN => '484',
            self::MXV => '979',
            self::MYR => '458',
            self::MZN => '943',
            self::NAD => '516',
            self::NGN => '566',
            self::NIO => '558',
            self::NOK => '578',
            self::NPR => '524',
            self::NZD => '554',
            self::OMR => '512',
            self::PAB => '590',
            self::PEN => '604',
            self::PGK => '598',
            self::PHP => '608',
            self::PKR => '586',
            self::PLN => '985',
            self::PYG => '600',
            self::QAR => '634',
            self::RON => '946',
            self::RSD => '941',
            self::RUB => '643',
            self::RWF => '646',
            self::SAR => '682',
            self::SBD => '090',
            self::SCR => '690',
            self::SDG => '938',
            self::SEK => '752',
            self::SGD => '702',
            self::SHP => '654',
            self::SLL => '694',
            self::SOS => '706',
            self::SRD => '968',
            self::SSP => '728',
            self::STN => '930',
            self::SVC => '222',
            self::SYP => '760',
            self::SZL => '748',
            self::THB => '764',
            self::TJS => '972',
            self::TMT => '934',
            self::TND => '788',
            self::TOP => '776',
            self::TRY => '949',
            self::TTD => '780',
            self::TWD => '901',
            self::TZS => '834',
            self::UAH => '980',
            self::UGX => '800',
            self::USD => '840',
            self::USN => '997',
            self::UYI => '940',
            self::UYU => '858',
            self::UYW => '927',
            self::UZS => '860',
            self::VED => '926',
            self::VES => '928',
            self::VND => '704',
            self::VUV => '548',
            self::WST => '882',
            self::XAF => '950',
            self::XAG => '961',
            self::XAU => '959',
            self::XBA => '955',
            self::XBB => '956',
            self::XBC => '957',
            self::XBD => '958',
            self::XCD => '951',
            self::XDR => '960',
            self::XOF => '952',
            self::XPD => '964',
            self::XPF => '953',
            self::XPT => '962',
            self::XSU => '994',
            self::XTS => '963',
            self::XUA => '965',
            self::XXX => '999',
            self::YER => '886',
            self::ZAR => '710',
            self::ZMW => '967',
            self::ZWL => '932',
        };
    }

    public function getName(): string
    {
        return match ($this) {
            self::AED => 'United Arab Emirates dirham',
            self::AFN => 'Afghan afghani',
            self::ALL => 'Albanian lek',
            self::AMD => 'Armenian dram',
            self::ANG => 'Netherlands Antillean guilder',
            self::AOA => 'Angolan kwanza',
            self::ARS => 'Argentine peso',
            self::AUD => 'Australian dollar',
            self::AWG => 'Aruban florin',
            self::AZN => 'Azerbaijani manat',
            self::BAM => 'Bosnia and Herzegovina convertible mark',
            self::BBD => 'Barbados dollar',
            self::BDT => 'Bangladeshi taka',
            self::BGN => 'Bulgarian lev',
            self::BHD => 'Bahraini dinar',
            self::BIF => 'Burundian franc',
            self::BMD => 'Bermudian dollar',
            self::BND => 'Brunei dollar',
            self::BOB => 'Boliviano',
            self::BOV => 'Bolivian Mvdol (funds code)',
            self::BRL => 'Brazilian real',
            self::BSD => 'Bahamian dollar',
            self::BTN => 'Bhutanese ngultrum',
            self::BWP => 'Botswana pula',
            self::BYN => 'Belarusian ruble',
            self::BZD => 'Belize dollar',
            self::CAD => 'Canadian dollar',
            self::CDF => 'Congolese franc',
            self::CHE => 'WIR euro (complementary currency)',
            self::CHF => 'Swiss franc',
            self::CHW => 'WIR franc (complementary currency)',
            self::CLF => 'Unidad de Fomento (funds code)',
            self::CLP => 'Chilean peso',
            self::CNY => 'Chinese yuan',
            self::COP => 'Colombian peso',
            self::COU => 'Unidad de Valor Real (UVR) (funds code)',
            self::CRC => 'Costa Rican colon',
            self::CUC => 'Cuban convertible peso',
            self::CUP => 'Cuban peso',
            self::CVE => 'Cape Verdean escudo',
            self::CZK => 'Czech koruna',
            self::DJF => 'Djiboutian franc',
            self::DKK => 'Danish krone',
            self::DOP => 'Dominican peso',
            self::DZD => 'Algerian dinar',
            self::EGP => 'Egyptian pound',
            self::ERN => 'Eritrean nakfa',
            self::ETB => 'Ethiopian birr',
            self::EUR => 'Euro',
            self::FJD => 'Fiji dollar',
            self::FKP => 'Falkland Islands pound',
            self::GBP => 'Pound sterling',
            self::GEL => 'Georgian lari',
            self::GHS => 'Ghanaian cedi',
            self::GIP => 'Gibraltar pound',
            self::GMD => 'Gambian dalasi',
            self::GNF => 'Guinean franc',
            self::GTQ => 'Guatemalan quetzal',
            self::GYD => 'Guyanese dollar',
            self::HKD => 'Hong Kong dollar',
            self::HNL => 'Honduran lempira',
            self::HRK => 'Croatian kuna',
            self::HTG => 'Haitian gourde',
            self::HUF => 'Hungarian forint',
            self::IDR => 'Indonesian rupiah',
            self::ILS => 'Israeli new shekel',
            self::INR => 'Indian rupee',
            self::IQD => 'Iraqi dinar',
            self::IRR => 'Iranian rial',
            self::ISK => 'Icelandic króna',
            self::JMD => 'Jamaican dollar',
            self::JOD => 'Jordanian dinar',
            self::JPY => 'Japanese yen',
            self::KES => 'Kenyan shilling',
            self::KGS => 'Kyrgyzstani som',
            self::KHR => 'Cambodian riel',
            self::KMF => 'Comoro franc',
            self::KPW => 'North Korean won',
            self::KRW => 'South Korean won',
            self::KWD => 'Kuwaiti dinar',
            self::KYD => 'Cayman Islands dollar',
            self::KZT => 'Kazakhstani tenge',
            self::LAK => 'Lao kip',
            self::LBP => 'Lebanese pound',
            self::LKR => 'Sri Lankan rupee',
            self::LRD => 'Liberian dollar',
            self::LSL => 'Lesotho loti',
            self::LYD => 'Libyan dinar',
            self::MAD => 'Moroccan dirham',
            self::MDL => 'Moldovan leu',
            self::MGA => 'Malagasy ariary',
            self::MKD => 'Macedonian denar',
            self::MMK => 'Myanmar kyat',
            self::MNT => 'Mongolian tögrög',
            self::MOP => 'Macanese pataca',
            self::MRU => 'Mauritanian ouguiya',
            self::MUR => 'Mauritian rupee',
            self::MVR => 'Maldivian rufiyaa',
            self::MWK => 'Malawian kwacha',
            self::MXN => 'Mexican peso',
            self::MXV => 'Mexican Unidad de Inversion (UDI) (funds code)',
            self::MYR => 'Malaysian ringgit',
            self::MZN => 'Mozambican metical',
            self::NAD => 'Namibian dollar',
            self::NGN => 'Nigerian naira',
            self::NIO => 'Nicaraguan córdoba',
            self::NOK => 'Norwegian krone',
            self::NPR => 'Nepalese rupee',
            self::NZD => 'New Zealand dollar',
            self::OMR => 'Omani rial',
            self::PAB => 'Panamanian balboa',
            self::PEN => 'Peruvian sol',
            self::PGK => 'Papua New Guinean kina',
            self::PHP => 'Philippine peso',
            self::PKR => 'Pakistani rupee',
            self::PLN => 'Polish złoty',
            self::PYG => 'Paraguayan guaraní',
            self::QAR => 'Qatari riyal',
            self::RON => 'Romanian leu',
            self::RSD => 'Serbian dinar',
            self::RUB => 'Russian ruble',
            self::RWF => 'Rwandan franc',
            self::SAR => 'Saudi riyal',
            self::SBD => 'Solomon Islands dollar',
            self::SCR => 'Seychelles rupee',
            self::SDG => 'Sudanese pound',
            self::SEK => 'Swedish krona',
            self::SGD => 'Singapore dollar',
            self::SHP => 'Saint Helena pound',
            self::SLL => 'Sierra Leonean leone',
            self::SOS => 'Somali shilling',
            self::SRD => 'Surinamese dollar',
            self::SSP => 'South Sudanese pound',
            self::STN => 'São Tomé and Príncipe dobra',
            self::SVC => 'Salvadoran colón',
            self::SYP => 'Syrian pound',
            self::SZL => 'Swazi lilangeni',
            self::THB => 'Thai baht',
            self::TJS => 'Tajikistani somoni',
            self::TMT => 'Turkmenistan manat',
            self::TND => 'Tunisian dinar',
            self::TOP => 'Tongan paʻanga',
            self::TRY => 'Turkish lira',
            self::TTD => 'Trinidad and Tobago dollar',
            self::TWD => 'New Taiwan dollar',
            self::TZS => 'Tanzanian shilling',
            self::UAH => 'Ukrainian hryvnia',
            self::UGX => 'Ugandan shilling',
            self::USD => 'United States dollar',
            self::USN => 'United States dollar',
            self::UYI => 'Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)',
            self::UYU => 'Uruguayan peso',
            self::UYW => 'Unidad previsional',
            self::UZS => 'Uzbekistan som',
            self::VED => 'Venezuelan bolívar digital',
            self::VES => 'Venezuelan bolívar soberano',
            self::VND => 'Vietnamese đồng',
            self::VUV => 'Vanuatu vatu',
            self::WST => 'Samoan tala',
            self::XAF => 'CFA franc BEAC',
            self::XAG => 'Silver (one troy ounce)',
            self::XAU => 'Gold (one troy ounce)',
            self::XBA => 'European Composite Unit (EURCO) (bond market unit)',
            self::XBB => 'European Monetary Unit (E.M.U.-6) (bond market unit)',
            self::XBC => 'European Unit of Account 9 (E.U.A.-9) (bond market unit)',
            self::XBD => 'European Unit of Account 17 (E.U.A.-17) (bond market unit)',
            self::XCD => 'East Caribbean dollar',
            self::XDR => 'Special drawing rights',
            self::XOF => 'CFA franc BCEAO',
            self::XPD => 'Palladium (one troy ounce)',
            self::XPF => 'CFP franc (franc Pacifique)',
            self::XPT => 'Platinum (one troy ounce)',
            self::XSU => 'SUCRE 	Unified System for Regional Compensation (SUCRE)[17]',
            self::XTS => 'Code reserved for testing',
            self::XUA => 'ADB Unit of Account 	African Development Bank[18]',
            self::XXX => 'No currency',
            self::YER => 'Yemeni rial',
            self::ZAR => 'South African rand',
            self::ZMW => 'Zambian kwacha',
            self::ZWL => 'Zimbabwean dollar',
        };
    }

    public function getSymbol() : string
    {
        return match($this) {
            self::AFN => '؋',
            self::MGA => 'Ar',
            self::THB => '฿',
            self::PAB => 'B/.',
            self::ETB, self::BYN => 'Br',
            self::VES => 'Bs.S.',
            self::GHS => '₵',
            self::CRC => '₡',
            self::NIO => 'C$',
            self::GMD => 'D',
            self::MKD => 'ден',
            self::DZD => 'دج',
            self::BHD => '.د.ب',
            self::IQD => 'د.ع',
            self::JOD => 'د.أ',
            self::KWD => 'د.ك',
            self::LYD => '.د',
            self::RSD => 'дин',
            self::TND => 'د.ت',
            self::MAD => 'د.م.',
            self::AED => 'د.إ',
            self::STN => 'Db',
            self::AUD => 'A$',
            self::BBD => 'Bds$',
            self::BMD => 'BD$',
            self::BZD => 'BZ$',
            self::CAD => 'CA$',
            self::FJD => 'FJ$',
            self::GYD => 'G$',
            self::HKD => 'HK$',
            self::JMD => 'J$',
            self::KYD => 'CI$',
            self::LRD => 'L$',
            self::NAD => 'N$',
            self::NZD => 'NZ$',
            self::SBD => 'SI$',
            self::SGD => 'S$',
            self::SRD => 'SRD',
            self::TWD => 'NT$',
            self::TTD => 'TT$',
            self::USD, self::USN, self::ARS => '$',
            self::XCD => 'EC$',
            self::CLP => 'CLP$',
            self::COP => 'COP$',
            self::CUP => '$MN',
            self::CUC => 'CUC$',
            self::DOP => 'RD$',
            self::MXN => 'Mex$',
            self::UYU => '$U',
            self::VND => '₫',
            self::AMD => '֏',
            self::CVE => 'Esc',
            self::EUR => '€',
            self::AWG, self::ANG => 'ƒ',
            self::HUF => 'Ft',
            self::BIF => 'FBu',
            self::XAF => 'FCFA',
            self::XOF => 'CFA',
            self::KMF => 'CF',
            self::CDF => 'FC',
            self::DJF => 'Fdj',
            self::GNF => 'GFr',
            self::CHF => 'SFr',
            self::RWF => 'FRw',
            self::HTG => 'G',
            self::PYG => '₲',
            self::UAH => '₴',
            self::LAK => '₭',
            self::CZK => 'Kč',
            self::AOA => 'Kz',
            self::DKK, self::NOK, self::SEK, self::ISK => 'Kr',
            self::HRK => 'kn',
            self::MMK, self::PGK, self::MWK, self::ZMW => 'K',
            self::GEL => '₾',
            self::ALL, self::RON, self::MDL, self::HNL => 'L',
            self::SLL => 'Le',
            self::BGN => 'лв.',
            self::SZL => 'E',
            self::TRY => '₺',
            self::LSL => 'M',
            self::AZN => '₼',
            self::BAM => 'KM',
            self::MZN => 'MT',
            self::ERN => 'Nfk',
            self::NGN => '₦',
            self::BTN => 'Nu.',
            self::MRU => 'UM',
            self::TOP => 'T$',
            self::MOP => 'MOP$',
            self::PHP => '₱',
            self::EGP => '£E',
            self::FKP, self::GIP, self::SHP, self::GBP => '£',
            self::SSP => 'SS£',
            self::SDG => '£SD',
            self::SYP => '£S',
            self::LBP => 'LL',
            self::BWP => 'P',
            self::GTQ => 'Q',
            self::ZAR => 'R',
            self::BRL => 'R$',
            self::IRR => '﷼',
            self::OMR => 'ر.ع.',
            self::QAR => 'ر.ق',
            self::SAR => 'ر.س',
            self::YER => 'ر.ي',
            self::KHR => '៛',
            self::MYR => 'RM',
            self::RUB => '₽',
            self::MVR => 'Rf.',
            self::INR => '₹',
            self::MUR, self::PKR => 'Mr',
            self::NPR => 'रू',
            self::LKR => 'රු',
            self::SCR => 'SRe',
            self::IDR => 'Rp',
            self::ILS => '₪',
            self::TZS => 'Tsh',
            self::KES => 'Ksh',
            self::SOS => 'Sh.So.',
            self::UGX => 'USh',
            self::PEN => 'S/',
            self::XDR => 'SDR',
            self::KGS => 'сом',
            self::BDT => '৳',
            self::WST => 'WS$',
            self::KZT => '₸',
            self::MNT => '₮',
            self::VUV => 'VT',
            self::KPW, self::KRW => '₩',
            self::CNY, self::JPY => '¥',
            self::PLN => 'zł',
            default => '',
        };
    }

    public static function fromISO4217Code(int|string $code): self
    {
        $code = str_pad((string)$code, 3, '0', STR_PAD_LEFT);

        return match ($code) {
            '784' => self::AED,
            '971' => self::AFN,
            '008' => self::ALL,
            '051' => self::AMD,
            '532' => self::ANG,
            '973' => self::AOA,
            '032' => self::ARS,
            '036' => self::AUD,
            '533' => self::AWG,
            '944' => self::AZN,
            '977' => self::BAM,
            '052' => self::BBD,
            '050' => self::BDT,
            '975' => self::BGN,
            '048' => self::BHD,
            '108' => self::BIF,
            '060' => self::BMD,
            '096' => self::BND,
            '068' => self::BOB,
            '984' => self::BOV,
            '986' => self::BRL,
            '044' => self::BSD,
            '064' => self::BTN,
            '072' => self::BWP,
            '933' => self::BYN,
            '084' => self::BZD,
            '124' => self::CAD,
            '976' => self::CDF,
            '947' => self::CHE,
            '756' => self::CHF,
            '948' => self::CHW,
            '990' => self::CLF,
            '152' => self::CLP,
            '156' => self::CNY,
            '170' => self::COP,
            '970' => self::COU,
            '188' => self::CRC,
            '931' => self::CUC,
            '192' => self::CUP,
            '132' => self::CVE,
            '203' => self::CZK,
            '262' => self::DJF,
            '208' => self::DKK,
            '214' => self::DOP,
            '012' => self::DZD,
            '818' => self::EGP,
            '232' => self::ERN,
            '230' => self::ETB,
            '978' => self::EUR,
            '242' => self::FJD,
            '238' => self::FKP,
            '826' => self::GBP,
            '981' => self::GEL,
            '936' => self::GHS,
            '292' => self::GIP,
            '270' => self::GMD,
            '324' => self::GNF,
            '320' => self::GTQ,
            '328' => self::GYD,
            '344' => self::HKD,
            '340' => self::HNL,
            '191' => self::HRK,
            '332' => self::HTG,
            '348' => self::HUF,
            '360' => self::IDR,
            '376' => self::ILS,
            '356' => self::INR,
            '368' => self::IQD,
            '364' => self::IRR,
            '352' => self::ISK,
            '388' => self::JMD,
            '400' => self::JOD,
            '392' => self::JPY,
            '404' => self::KES,
            '417' => self::KGS,
            '116' => self::KHR,
            '174' => self::KMF,
            '408' => self::KPW,
            '410' => self::KRW,
            '414' => self::KWD,
            '136' => self::KYD,
            '398' => self::KZT,
            '418' => self::LAK,
            '422' => self::LBP,
            '144' => self::LKR,
            '430' => self::LRD,
            '426' => self::LSL,
            '434' => self::LYD,
            '504' => self::MAD,
            '498' => self::MDL,
            '969' => self::MGA,
            '807' => self::MKD,
            '104' => self::MMK,
            '496' => self::MNT,
            '446' => self::MOP,
            '929' => self::MRU,
            '480' => self::MUR,
            '462' => self::MVR,
            '454' => self::MWK,
            '484' => self::MXN,
            '979' => self::MXV,
            '458' => self::MYR,
            '943' => self::MZN,
            '516' => self::NAD,
            '566' => self::NGN,
            '558' => self::NIO,
            '578' => self::NOK,
            '524' => self::NPR,
            '554' => self::NZD,
            '512' => self::OMR,
            '590' => self::PAB,
            '604' => self::PEN,
            '598' => self::PGK,
            '608' => self::PHP,
            '586' => self::PKR,
            '985' => self::PLN,
            '600' => self::PYG,
            '634' => self::QAR,
            '946' => self::RON,
            '941' => self::RSD,
            '643' => self::RUB,
            '646' => self::RWF,
            '682' => self::SAR,
            '090' => self::SBD,
            '690' => self::SCR,
            '938' => self::SDG,
            '752' => self::SEK,
            '702' => self::SGD,
            '654' => self::SHP,
            '694' => self::SLL,
            '706' => self::SOS,
            '968' => self::SRD,
            '728' => self::SSP,
            '930' => self::STN,
            '222' => self::SVC,
            '760' => self::SYP,
            '748' => self::SZL,
            '764' => self::THB,
            '972' => self::TJS,
            '934' => self::TMT,
            '788' => self::TND,
            '776' => self::TOP,
            '949' => self::TRY,
            '780' => self::TTD,
            '901' => self::TWD,
            '834' => self::TZS,
            '980' => self::UAH,
            '800' => self::UGX,
            '840' => self::USD,
            '997' => self::USN,
            '940' => self::UYI,
            '858' => self::UYU,
            '927' => self::UYW,
            '860' => self::UZS,
            '926' => self::VED,
            '928' => self::VES,
            '704' => self::VND,
            '548' => self::VUV,
            '882' => self::WST,
            '950' => self::XAF,
            '961' => self::XAG,
            '959' => self::XAU,
            '955' => self::XBA,
            '956' => self::XBB,
            '957' => self::XBC,
            '958' => self::XBD,
            '951' => self::XCD,
            '960' => self::XDR,
            '952' => self::XOF,
            '964' => self::XPD,
            '953' => self::XPF,
            '962' => self::XPT,
            '994' => self::XSU,
            '963' => self::XTS,
            '965' => self::XUA,
            '999' => self::XXX,
            '886' => self::YER,
            '710' => self::ZAR,
            '967' => self::ZMW,
            '932' => self::ZWL,
        };
    }

    public static function options() : array
    {
        $options = [];
        foreach (self::cases() as $option) {
            $options[$option->value] = sprintf('%s, %s', $option->getName(), $option->getSymbol());
        }

        return $options;
    }

    // Since most of the currencies have 2 decimals, it makes sense to process only exceptions
    public function getDecimalPlaces() : int
    {
        return match($this) {
            self::BHD,self::KWD,self::JOD,self::IQD,
            self::LYD,self::OMR,self::TND => 3,

            self::CLF, self::UYW => 4,

            self::BIF,self::DJF,self::GNF,self::ISK,
            self::JPY,self::KMF,self::CLP,self::KRW,
            self::PYG,self::RWF,self::UGX,self::UYI,
            self::VUV,self::VND,self::XAF,self::XOF,
            self::XPF,
                // These are the special currencies, they don't have info about decimal places
                // or it is not applicable, but we'll coalesce them to 0
            self::XAG,self::XAU,self::XBA,self::XBB,
            self::XBC,self::XBD,self::XDR,self::XPD,
            self::XPT,self::XSU,self::XTS,self::XXX,
            self::XUA => 0,

            default => 2,
        };
    }

    public function format(float $value, ?int $decimals = null) : string
    {
        return ltrim(sprintf('%s %s', self::getSymbol(), number_format($value, $decimals ?? self::getDecimalPlaces())));
    }
}
